#Encoder config -------------------
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#Battery config -------------------
CONFIG_ZMK_BATTERY_REPORTING=y

#Sleep config -------------------
CONFIG_ZMK_IDLE_TIMEOUT=60000        # 入力なし→Idle移行までの時間(ms) BLE接続維持・遅延なし
CONFIG_ZMK_SLEEP=y                   # Deep Sleep有効化
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000 # Idle→Deep Sleep移行までの時間(ms) BLE切断・再接続が必要